update lpl e init script

diff --git a/lpl b/lpl
--- a/lpl
+++ b/lpl
@@ -18,6 +18,15 @@ case "$1" in
     docker cp ./init.sql database:/home/
     docker exec -i database psql -U APP -d labprog -f /home/init.sql
     ;;
+  config ) echo "Cargando configuración inicial"
+    docker cp ./init.sql database:/home/ 1>/dev/null
+    docker exec -i database psql -U APP -d labprog -f /home/init.sql 1>/dev/null 2>/dev/null
+    if [ $? -eq 0 ]; then
+      echo "El script SQL se ejecutó correctamente."
+    else
+      echo "Hubo un error al ejecutar el script SQL."
+    fi
+    ;;
   up ) echo "Iniciando servidores.."
     docker compose -f docker-compose.yml up -d
     ;;
